# Generated by Django 6.1.1 on 2026-09-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Uncheck to mark this teacher temporarily unavailable (e.g. on leave). The scheduler will automatically look for a qualified substitute.'),
        ),
    ]
