# Generated by Django 6.1.1 on 2026-09-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_teacher_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='lab_duration_slots',
            field=models.PositiveIntegerField(default=2, help_text='Duration in continuous time slots per lab session (e.g. 2 hours).'),
        ),
        migrations.AddField(
            model_name='subject',
            name='lab_sessions_per_week',
            field=models.PositiveIntegerField(default=1, help_text='Number of lab sessions per week (default 1 if requires_lab is True).'),
        ),
    ]
