# Generated by Django 6.1.1 on 2026-10-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_subject_lab_duration_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='preferred_lab_timing',
            field=models.CharField(choices=[('MORNING', 'Morning Labs'), ('AFTERNOON', 'Post-Lunch Labs'), ('NO_PREF', 'No Preference')], default='NO_PREF', help_text='Does this division prefer morning or afternoon lab sessions?', max_length=10),
        ),
        migrations.AddField(
            model_name='division',
            name='preferred_light_day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('NONE', 'No Light Day')], default='NONE', help_text='Which day should have fewer/lighter sessions? (e.g. Friday)', max_length=4),
        ),
        migrations.AddField(
            model_name='division',
            name='preferred_shift',
            field=models.CharField(choices=[('MORNING', 'Morning Focus (09:00–12:00)'), ('BALANCED', 'Balanced / Standard'), ('AFTERNOON', 'Afternoon / Late Start (11:00+)')], default='BALANCED', help_text='Does this division prefer morning, afternoon, or balanced sessions?', max_length=10),
        ),
        migrations.AddField(
            model_name='division',
            name='scheduling_priority',
            field=models.PositiveIntegerField(default=0, help_text='Scheduling priority (higher wins first pick of preferred slots). Automatically derived from year + performance, but can be overridden.'),
        ),
        migrations.AlterField(
            model_name='division',
            name='performance_percentage',
            field=models.FloatField(default=0.0, help_text='Previous semester average %. Higher % → higher scheduling priority.'),
        ),
    ]
